<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: curl.proto

namespace Php\Micro\Grpc\Curl;

use Mix\Grpc;
use Mix\Context\Context;

interface CurlInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "php.micro.grpc.curl.Curl";

    /**
    * @param Context $context
    * @param Request $request
    * @return Response
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Get(Context $context, Request $request): Response;
}
