<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: user.proto

namespace Php\Micro\Srv\User;

use Mix\Grpc;
use Mix\Context\Context;

interface UserInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "php.micro.srv.user.User";

    /**
    * @param Context $ctx
    * @param Request $in
    * @return Response
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Add(Context $ctx, Request $req): Response;
}
