<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace Php\Micro\Grpc\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>php.micro.grpc.user.GetResponse</code>
 */
class GetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>.php.micro.grpc.user.Userinfo userinfo = 2;</code>
     */
    protected $userinfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type \Php\Micro\Grpc\User\Userinfo $userinfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.php.micro.grpc.user.Userinfo userinfo = 2;</code>
     * @return \Php\Micro\Grpc\User\Userinfo
     */
    public function getUserinfo()
    {
        return $this->userinfo;
    }

    /**
     * Generated from protobuf field <code>.php.micro.grpc.user.Userinfo userinfo = 2;</code>
     * @param \Php\Micro\Grpc\User\Userinfo $var
     * @return $this
     */
    public function setUserinfo($var)
    {
        GPBUtil::checkMessage($var, \Php\Micro\Grpc\User\Userinfo::class);
        $this->userinfo = $var;

        return $this;
    }

}

