<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: user.proto

namespace Php\Micro\Grpc\User;

use Mix\Grpc;
use Mix\Context\Context;

class UserClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param AddRequest $request
    * @param array $options
    * @return AddResponse
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Add(Context $context, AddRequest $request, array $options = []): AddResponse
    {
        return $this->_simpleRequest('/php.micro.grpc.user.User/Add', $context, $request, new AddResponse(), $options);
    }

    /**
    * @param Context $context
    * @param GetRequest $request
    * @param array $options
    * @return GetResponse
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Get(Context $context, GetRequest $request, array $options = []): GetResponse
    {
        return $this->_simpleRequest('/php.micro.grpc.user.User/Get', $context, $request, new GetResponse(), $options);
    }
}
