<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: user.proto

namespace Php\Micro\Grpc\User;

use Mix\Grpc;
use Mix\Context\Context;

interface UserInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "php.micro.grpc.user.User";

    /**
    * @param Context $context
    * @param AddRequest $request
    * @return AddResponse
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Add(Context $context, AddRequest $request): AddResponse;

    /**
    * @param Context $context
    * @param GetRequest $request
    * @return GetResponse
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Get(Context $context, GetRequest $request): GetResponse;
}
