<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: user.proto

namespace Php\Micro\Grpc\User;

use Mix\Grpc;
use Mix\Context\Context;

interface UserInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "php.micro.grpc.user.User";

    /**
    * @param Context $context
    * @param Request $request
    * @return Response
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Add(Context $context, Request $request): Response;
}
