<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curl.proto

namespace GPBMetadata;

class Curl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a0a6375726c2e70726f746f12127068702e6d6963726f2e7372762e6375726c22160a0752657175657374120b0a0375726c18012001280922290a08526573706f6e7365120e0a06726573756c74180120012809120d0a056572726f72180220012809324a0a044375726c12420a03476574121b2e7068702e6d6963726f2e7372762e6375726c2e526571756573741a1c2e7068702e6d6963726f2e7372762e6375726c2e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

