<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a0a757365722e70726f746f12137068702e6d6963726f2e677270632e7573657222330a0752657175657374120c0a046e616d65180120012809120b0a03616765180220012809120d0a05656d61696c180320012809221a0a08526573706f6e7365120e0a06737461747573180120012809324c0a045573657212440a03416464121c2e7068702e6d6963726f2e677270632e757365722e526571756573741a1d2e7068702e6d6963726f2e677270632e757365722e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

