<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: curl.proto

namespace Php\Micro\Srv\Curl;

use Mix\Grpc;
use Mix\Context\Context;

interface CurlInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "php.micro.srv.curl.Curl";

    /**
    * @param Context $ctx
    * @param Request $in
    * @return Response
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Get(Context $ctx, Request $req): Response;
}
